services:
  - type: web
    name: churnsense
    env: python
    buildCommand: ./build.sh
    startCommand: gunicorn --worker-tmp-dir /dev/shm wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.13
      - key: FLASK_ENV
        value: production
      - key: PYTHONUNBUFFERED
        value: true
      - key: PYTHONDONTWRITEBYTECODE
        value: 1
      - key: PIP_NO_CACHE_DIR
        value: off
      - key: PIP_DISABLE_PIP_VERSION_CHECK
        value: on
    plan: free
    numInstances: 1
    healthCheckPath: /
    autoDeploy: true
